name: Check PRs for conflicts

on:
  pull_request_target:
    types: [synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PRs are dirty
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "has merge conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: |
            This pull request has conflicts, please rebase to resolve those before we can evaluate the pull request.

